### ISSUE TITLE
request for some features:

### ISSUE THREAD

**Issue by skywind3000** [DPISA/atom-user-commands#1]
atom-user-commands is very useful for me when I am switching from EditPlus/NotePad++
some feature is very important for me, but it takes me a lot of time to master javascript or coffee.
That's why I am here to ask for help:
1. Could bottom panel be resize-able ? Let me decide the size instead of auto resize by how many lines.
2. Could bottom panel be closed ? A CLOSE button is needed.
3. Clean the text before each command execution, some compiler errors could be more than 1k lines.
4. {absPath} {path} could be set to environment as ATOM_USER_CMD_ABSPATH, before executing. 
5. The file will be open if its name in the compiler error output of bottom panel clicked by user. (the regular expression of filename and line number could be changed in my user config file).

---

That would be much helpful.

**Comment by pakopa** [comment]
Your pull request https://github.com/DPISA/atom-user-commands/pull/2 has been merged. 

I will take a look to linking the file names in the console.

**Comment by pakopa** [comment]
[atom-shell-commands](https://github.com/skywind3000/atom-shell-commands) is far ahead in development.
